/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppStudyNotebookRouteImport } from './routes/app.study-notebook'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppModelAnswersRouteImport } from './routes/app.model-answers'
import { Route as AppMiniPaperRouteImport } from './routes/app.mini-paper'
import { Route as AppKeywordsRouteImport } from './routes/app.keywords'
import { Route as AppGenerateRouteImport } from './routes/app.generate'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCommonMistakesRouteImport } from './routes/app.common-mistakes'
import { Route as AppClassroomRouteImport } from './routes/app.classroom'
import { Route as AppAiTutorRouteImport } from './routes/app.ai-tutor'
import { Route as AppPracticeIndexRouteImport } from './routes/app.practice.index'
import { Route as AppTopicsSubjectRouteImport } from './routes/app.topics.$subject'
import { Route as AppQuestionIdRouteImport } from './routes/app.question.$id'
import { Route as AppClassroomClassIdRouteImport } from './routes/app.classroom.$classId'
import { Route as AppClassroomTaskClassIdRouteImport } from './routes/app.classroom-task.$classId'
import { Route as AppClassroomStreamClassIdRouteImport } from './routes/app.classroom-stream.$classId'
import { Route as AppPracticeSubjectTopicRouteImport } from './routes/app.practice.$subject.$topic'
import { Route as AppClassroomClassIdStreamRouteImport } from './routes/app.classroom.$classId.stream'
import { Route as AppClassroomAssignmentClassIdAssignmentIdRouteImport } from './routes/app.classroom-assignment.$classId.$assignmentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyNotebookRoute = AppStudyNotebookRouteImport.update({
  id: '/study-notebook',
  path: '/study-notebook',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppModelAnswersRoute = AppModelAnswersRouteImport.update({
  id: '/model-answers',
  path: '/model-answers',
  getParentRoute: () => AppRoute,
} as any)
const AppMiniPaperRoute = AppMiniPaperRouteImport.update({
  id: '/mini-paper',
  path: '/mini-paper',
  getParentRoute: () => AppRoute,
} as any)
const AppKeywordsRoute = AppKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommonMistakesRoute = AppCommonMistakesRouteImport.update({
  id: '/common-mistakes',
  path: '/common-mistakes',
  getParentRoute: () => AppRoute,
} as any)
const AppClassroomRoute = AppClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTutorRoute = AppAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsSubjectRoute = AppTopicsSubjectRouteImport.update({
  id: '/topics/$subject',
  path: '/topics/$subject',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionIdRoute = AppQuestionIdRouteImport.update({
  id: '/question/$id',
  path: '/question/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClassroomClassIdRoute = AppClassroomClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => AppClassroomRoute,
} as any)
const AppClassroomTaskClassIdRoute = AppClassroomTaskClassIdRouteImport.update({
  id: '/classroom-task/$classId',
  path: '/classroom-task/$classId',
  getParentRoute: () => AppRoute,
} as any)
const AppClassroomStreamClassIdRoute =
  AppClassroomStreamClassIdRouteImport.update({
    id: '/classroom-stream/$classId',
    path: '/classroom-stream/$classId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPracticeSubjectTopicRoute = AppPracticeSubjectTopicRouteImport.update({
  id: '/practice/$subject/$topic',
  path: '/practice/$subject/$topic',
  getParentRoute: () => AppRoute,
} as any)
const AppClassroomClassIdStreamRoute =
  AppClassroomClassIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => AppClassroomClassIdRoute,
  } as any)
const AppClassroomAssignmentClassIdAssignmentIdRoute =
  AppClassroomAssignmentClassIdAssignmentIdRouteImport.update({
    id: '/classroom-assignment/$classId/$assignmentId',
    path: '/classroom-assignment/$classId/$assignmentId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/classroom': typeof ClassroomRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-tutor': typeof AppAiTutorRoute
  '/app/classroom': typeof AppClassroomRouteWithChildren
  '/app/common-mistakes': typeof AppCommonMistakesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/mini-paper': typeof AppMiniPaperRoute
  '/app/model-answers': typeof AppModelAnswersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/review': typeof AppReviewRoute
  '/app/study-notebook': typeof AppStudyNotebookRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/classroom-stream/$classId': typeof AppClassroomStreamClassIdRoute
  '/app/classroom-task/$classId': typeof AppClassroomTaskClassIdRoute
  '/app/classroom/$classId': typeof AppClassroomClassIdRouteWithChildren
  '/app/question/$id': typeof AppQuestionIdRoute
  '/app/topics/$subject': typeof AppTopicsSubjectRoute
  '/app/practice/': typeof AppPracticeIndexRoute
  '/app/classroom-assignment/$classId/$assignmentId': typeof AppClassroomAssignmentClassIdAssignmentIdRoute
  '/app/classroom/$classId/stream': typeof AppClassroomClassIdStreamRoute
  '/app/practice/$subject/$topic': typeof AppPracticeSubjectTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classroom': typeof ClassroomRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-tutor': typeof AppAiTutorRoute
  '/app/classroom': typeof AppClassroomRouteWithChildren
  '/app/common-mistakes': typeof AppCommonMistakesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/mini-paper': typeof AppMiniPaperRoute
  '/app/model-answers': typeof AppModelAnswersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/review': typeof AppReviewRoute
  '/app/study-notebook': typeof AppStudyNotebookRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app': typeof AppIndexRoute
  '/app/classroom-stream/$classId': typeof AppClassroomStreamClassIdRoute
  '/app/classroom-task/$classId': typeof AppClassroomTaskClassIdRoute
  '/app/classroom/$classId': typeof AppClassroomClassIdRouteWithChildren
  '/app/question/$id': typeof AppQuestionIdRoute
  '/app/topics/$subject': typeof AppTopicsSubjectRoute
  '/app/practice': typeof AppPracticeIndexRoute
  '/app/classroom-assignment/$classId/$assignmentId': typeof AppClassroomAssignmentClassIdAssignmentIdRoute
  '/app/classroom/$classId/stream': typeof AppClassroomClassIdStreamRoute
  '/app/practice/$subject/$topic': typeof AppPracticeSubjectTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/classroom': typeof ClassroomRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-tutor': typeof AppAiTutorRoute
  '/app/classroom': typeof AppClassroomRouteWithChildren
  '/app/common-mistakes': typeof AppCommonMistakesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/mini-paper': typeof AppMiniPaperRoute
  '/app/model-answers': typeof AppModelAnswersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/review': typeof AppReviewRoute
  '/app/study-notebook': typeof AppStudyNotebookRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/classroom-stream/$classId': typeof AppClassroomStreamClassIdRoute
  '/app/classroom-task/$classId': typeof AppClassroomTaskClassIdRoute
  '/app/classroom/$classId': typeof AppClassroomClassIdRouteWithChildren
  '/app/question/$id': typeof AppQuestionIdRoute
  '/app/topics/$subject': typeof AppTopicsSubjectRoute
  '/app/practice/': typeof AppPracticeIndexRoute
  '/app/classroom-assignment/$classId/$assignmentId': typeof AppClassroomAssignmentClassIdAssignmentIdRoute
  '/app/classroom/$classId/stream': typeof AppClassroomClassIdStreamRoute
  '/app/practice/$subject/$topic': typeof AppPracticeSubjectTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/classroom'
    | '/login'
    | '/signup'
    | '/app/ai-tutor'
    | '/app/classroom'
    | '/app/common-mistakes'
    | '/app/dashboard'
    | '/app/flashcards'
    | '/app/generate'
    | '/app/keywords'
    | '/app/mini-paper'
    | '/app/model-answers'
    | '/app/profile'
    | '/app/progress'
    | '/app/review'
    | '/app/study-notebook'
    | '/app/subjects'
    | '/app/'
    | '/app/classroom-stream/$classId'
    | '/app/classroom-task/$classId'
    | '/app/classroom/$classId'
    | '/app/question/$id'
    | '/app/topics/$subject'
    | '/app/practice/'
    | '/app/classroom-assignment/$classId/$assignmentId'
    | '/app/classroom/$classId/stream'
    | '/app/practice/$subject/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classroom'
    | '/login'
    | '/signup'
    | '/app/ai-tutor'
    | '/app/classroom'
    | '/app/common-mistakes'
    | '/app/dashboard'
    | '/app/flashcards'
    | '/app/generate'
    | '/app/keywords'
    | '/app/mini-paper'
    | '/app/model-answers'
    | '/app/profile'
    | '/app/progress'
    | '/app/review'
    | '/app/study-notebook'
    | '/app/subjects'
    | '/app'
    | '/app/classroom-stream/$classId'
    | '/app/classroom-task/$classId'
    | '/app/classroom/$classId'
    | '/app/question/$id'
    | '/app/topics/$subject'
    | '/app/practice'
    | '/app/classroom-assignment/$classId/$assignmentId'
    | '/app/classroom/$classId/stream'
    | '/app/practice/$subject/$topic'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/classroom'
    | '/login'
    | '/signup'
    | '/app/ai-tutor'
    | '/app/classroom'
    | '/app/common-mistakes'
    | '/app/dashboard'
    | '/app/flashcards'
    | '/app/generate'
    | '/app/keywords'
    | '/app/mini-paper'
    | '/app/model-answers'
    | '/app/profile'
    | '/app/progress'
    | '/app/review'
    | '/app/study-notebook'
    | '/app/subjects'
    | '/app/'
    | '/app/classroom-stream/$classId'
    | '/app/classroom-task/$classId'
    | '/app/classroom/$classId'
    | '/app/question/$id'
    | '/app/topics/$subject'
    | '/app/practice/'
    | '/app/classroom-assignment/$classId/$assignmentId'
    | '/app/classroom/$classId/stream'
    | '/app/practice/$subject/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ClassroomRoute: typeof ClassroomRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study-notebook': {
      id: '/app/study-notebook'
      path: '/study-notebook'
      fullPath: '/app/study-notebook'
      preLoaderRoute: typeof AppStudyNotebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/model-answers': {
      id: '/app/model-answers'
      path: '/model-answers'
      fullPath: '/app/model-answers'
      preLoaderRoute: typeof AppModelAnswersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mini-paper': {
      id: '/app/mini-paper'
      path: '/mini-paper'
      fullPath: '/app/mini-paper'
      preLoaderRoute: typeof AppMiniPaperRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keywords': {
      id: '/app/keywords'
      path: '/keywords'
      fullPath: '/app/keywords'
      preLoaderRoute: typeof AppKeywordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generate': {
      id: '/app/generate'
      path: '/generate'
      fullPath: '/app/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/common-mistakes': {
      id: '/app/common-mistakes'
      path: '/common-mistakes'
      fullPath: '/app/common-mistakes'
      preLoaderRoute: typeof AppCommonMistakesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classroom': {
      id: '/app/classroom'
      path: '/classroom'
      fullPath: '/app/classroom'
      preLoaderRoute: typeof AppClassroomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-tutor': {
      id: '/app/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/app/ai-tutor'
      preLoaderRoute: typeof AppAiTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/practice/': {
      id: '/app/practice/'
      path: '/practice'
      fullPath: '/app/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/topics/$subject': {
      id: '/app/topics/$subject'
      path: '/topics/$subject'
      fullPath: '/app/topics/$subject'
      preLoaderRoute: typeof AppTopicsSubjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/question/$id': {
      id: '/app/question/$id'
      path: '/question/$id'
      fullPath: '/app/question/$id'
      preLoaderRoute: typeof AppQuestionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classroom/$classId': {
      id: '/app/classroom/$classId'
      path: '/$classId'
      fullPath: '/app/classroom/$classId'
      preLoaderRoute: typeof AppClassroomClassIdRouteImport
      parentRoute: typeof AppClassroomRoute
    }
    '/app/classroom-task/$classId': {
      id: '/app/classroom-task/$classId'
      path: '/classroom-task/$classId'
      fullPath: '/app/classroom-task/$classId'
      preLoaderRoute: typeof AppClassroomTaskClassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classroom-stream/$classId': {
      id: '/app/classroom-stream/$classId'
      path: '/classroom-stream/$classId'
      fullPath: '/app/classroom-stream/$classId'
      preLoaderRoute: typeof AppClassroomStreamClassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/practice/$subject/$topic': {
      id: '/app/practice/$subject/$topic'
      path: '/practice/$subject/$topic'
      fullPath: '/app/practice/$subject/$topic'
      preLoaderRoute: typeof AppPracticeSubjectTopicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classroom/$classId/stream': {
      id: '/app/classroom/$classId/stream'
      path: '/stream'
      fullPath: '/app/classroom/$classId/stream'
      preLoaderRoute: typeof AppClassroomClassIdStreamRouteImport
      parentRoute: typeof AppClassroomClassIdRoute
    }
    '/app/classroom-assignment/$classId/$assignmentId': {
      id: '/app/classroom-assignment/$classId/$assignmentId'
      path: '/classroom-assignment/$classId/$assignmentId'
      fullPath: '/app/classroom-assignment/$classId/$assignmentId'
      preLoaderRoute: typeof AppClassroomAssignmentClassIdAssignmentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppClassroomClassIdRouteChildren {
  AppClassroomClassIdStreamRoute: typeof AppClassroomClassIdStreamRoute
}

const AppClassroomClassIdRouteChildren: AppClassroomClassIdRouteChildren = {
  AppClassroomClassIdStreamRoute: AppClassroomClassIdStreamRoute,
}

const AppClassroomClassIdRouteWithChildren =
  AppClassroomClassIdRoute._addFileChildren(AppClassroomClassIdRouteChildren)

interface AppClassroomRouteChildren {
  AppClassroomClassIdRoute: typeof AppClassroomClassIdRouteWithChildren
}

const AppClassroomRouteChildren: AppClassroomRouteChildren = {
  AppClassroomClassIdRoute: AppClassroomClassIdRouteWithChildren,
}

const AppClassroomRouteWithChildren = AppClassroomRoute._addFileChildren(
  AppClassroomRouteChildren,
)

interface AppRouteChildren {
  AppAiTutorRoute: typeof AppAiTutorRoute
  AppClassroomRoute: typeof AppClassroomRouteWithChildren
  AppCommonMistakesRoute: typeof AppCommonMistakesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppGenerateRoute: typeof AppGenerateRoute
  AppKeywordsRoute: typeof AppKeywordsRoute
  AppMiniPaperRoute: typeof AppMiniPaperRoute
  AppModelAnswersRoute: typeof AppModelAnswersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppReviewRoute: typeof AppReviewRoute
  AppStudyNotebookRoute: typeof AppStudyNotebookRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClassroomStreamClassIdRoute: typeof AppClassroomStreamClassIdRoute
  AppClassroomTaskClassIdRoute: typeof AppClassroomTaskClassIdRoute
  AppQuestionIdRoute: typeof AppQuestionIdRoute
  AppTopicsSubjectRoute: typeof AppTopicsSubjectRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
  AppClassroomAssignmentClassIdAssignmentIdRoute: typeof AppClassroomAssignmentClassIdAssignmentIdRoute
  AppPracticeSubjectTopicRoute: typeof AppPracticeSubjectTopicRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiTutorRoute: AppAiTutorRoute,
  AppClassroomRoute: AppClassroomRouteWithChildren,
  AppCommonMistakesRoute: AppCommonMistakesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppGenerateRoute: AppGenerateRoute,
  AppKeywordsRoute: AppKeywordsRoute,
  AppMiniPaperRoute: AppMiniPaperRoute,
  AppModelAnswersRoute: AppModelAnswersRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppReviewRoute: AppReviewRoute,
  AppStudyNotebookRoute: AppStudyNotebookRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClassroomStreamClassIdRoute: AppClassroomStreamClassIdRoute,
  AppClassroomTaskClassIdRoute: AppClassroomTaskClassIdRoute,
  AppQuestionIdRoute: AppQuestionIdRoute,
  AppTopicsSubjectRoute: AppTopicsSubjectRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
  AppClassroomAssignmentClassIdAssignmentIdRoute:
    AppClassroomAssignmentClassIdAssignmentIdRoute,
  AppPracticeSubjectTopicRoute: AppPracticeSubjectTopicRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ClassroomRoute: ClassroomRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
